### ISSUE TITLE
Fatal errors

### ISSUE THREAD

**Issue by ivukotic** [zfzf21/BASIC_changepoint#1]
Hi,

I have tried using your code but run into a bit of problem... here's output:
`MCEM Step...

 ************************** FATAL ERROR DETECTED **************************
 ************************** FATAL ERROR DETECTED **************************
 ************************** FATAL ERROR DETECTED **************************

Two fatal errors have been detected, the first was inappropriately ignored.
To prevent further fatal errors from being ignored this application will be
terminated immediately and you should go fix this buggy program.

The error message from this fatal error was:

Error detected at line 3386.
Error detected in file ../src/dlib/optimization/optimization_bobyqa.h.
Error detected in function double dlib::find_min_bobyqa(const funct&, T&, long int, const U&, const U&, double, double, long int) [with funct = dlib::negate_function_object<model_params_objective<bayesian_simultaneous_changepoint::NormalMeanModel> >; T = dlib::matrix<double, 0, 1>; U = dlib::matrix<double, 0, 1>].

Failing expression was x.size() + 2 <= npt && npt <= (x.size()+1)*(x.size()+2)/2 && 0 < rho_end && rho_end < rho_begin && min(x_upper - x_lower) > 2*rho_begin && min(x - x_lower) >= 0 && min(x_upper - x) >= 0.
	void find_min_bobyqa()
	 Invalid arguments have been given to this function
	 ntp in valid range: true
	 npt:                7
	 rho_begin:          10
	 rho_end:            1e-06
	 min(x_upper - x_lower) > 2*rho_begin:           true
	 min(x - x_lower) >= 0 && min(x_upper - x) >= 0: false`

It could be that there is something strange in my data, please let me know if you would like me to send you my data so you could reproduce the problem.

Thanks,
Ilija

**Comment by zfzf21** [comment]
Hi Ilija,

Thanks for the notification about this error. Yes, can you send me your
data, and also how you are running the program (i.e. the specific Python
call you used, if you are using the Python interface)? I'll try to
reproduce the problem on my machine.

I (and several others) have gotten this program to install and run
successfully on several different data sets, but it hasn't been tested
across a broad set of inputs and applications so it's possible you found a
robustness problem.

Best,
Zhou

**Comment by ivukotic** [comment]
Hi Zhou,

here the data and a very simple test case:
https://www.amazon.com/clouddrive/share/fZpdl3dhKRsmVpJXcUNuztrNY747JU0gdTTp1QU2HQx?ref_=cd_ph_share_link_copy
Please let me know if it is really a bug or I just did something stupid.

Thanks,
Ilija

--
Nullius in verba



On May 26, 2017, at 15:45 , zfzf21 <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Ilija,

Thanks for the notification about this error. Yes, can you send me your
data, and also how you are running the program (i.e. the specific Python
call you used, if you are using the Python interface)? I'll try to
reproduce the problem on my machine.

I (and several others) have gotten this program to install and run
successfully on several different data sets, but it hasn't been tested
across a broad set of inputs and applications so it's possible you found a
robustness problem.

Best,
Zhou

**Comment by zfzf21** [comment]
Hi Ilija,

The error is occurring because your input data matrix X has missing values (represented by np.nan). Unfortunately the current code does not support missing values in the data. As a work-around, you will need to impute the missing values yourself before fitting the model.

I have pushed a minor update which checks for missing and infinite values, and stops execution immediately if such values are found. (So the program would still fail for your data, but at an earlier stage and with an explicit error message.)

Best,
Zhou
